const PROVINCES = [
    { code: "A", name: "Alicante" },
    { code: "AB", name: "Albacete" },
    { code: "AL", name: "Almería" },
    { code: "AV", name: "Ávila" },
    { code: "B", name: "Barcelona" },
    { code: "BA", name: "Badajoz" },
    { code: "BI", name: "Bizcaia" },
    { code: "BU", name: "Burgos" },
    { code: "C", name: "La Coruña" },
    { code: "CA", name: "Cádiz" },
    { code: "CC", name: "Cáceres" },
    { code: "CE", name: "Ceuta" },
    { code: "CO", name: "Córdoba" },
    { code: "CR", name: "Ciudad Real" },
    { code: "CS", name: "Castellón" },
    { code: "CU", name: "Cuenca" },
    { code: "DS", name: "Desconocido" },
    { code: "EX", name: "Extranjero" },
    { code: "GC", name: "Las Palmas" },
    { code: "GI", name: "Gerona" },
    { code: "GR", name: "Granada" },
    { code: "GU", name: "Guadalajara" },
    { code: "H", name: "Huelva" },
    { code: "HU", name: "Huesca" },
    { code: "J", name: "Jaén" },
    { code: "L", name: "Lérida" },
    { code: "LE", name: "León" },
    { code: "LO", name: "La Rioja" },
    { code: "LU", name: "Lugo" },
    { code: "M", name: "Madrid" },
    { code: "MA", name: "Málaga" },
    { code: "ML", name: "Melilla" },
    { code: "MU", name: "Murcia" },
    { code: "NA", name: "Navarra" },
    { code: "O", name: "Asturias" },
    { code: "OU", name: "Orense" },
    { code: "P", name: "Palencia" },
    { code: "IB", name: "Baleares" },
    { code: "PO", name: "Pontevedra" },
    { code: "S", name: "Cantabria" },
    { code: "SA", name: "Salamanca" },
    { code: "SE", name: "Sevilla" },
    { code: "SG", name: "Segovia" },
    { code: "SO", name: "Soria" },
    { code: "SS", name: "Gipuzkoa" },
    { code: "T", name: "Tarragona" },
    { code: "TE", name: "Teruel" },
    { code: "TF", name: "Santa Cruz de Tenerife" },
    { code: "TO", name: "Toledo" },
    { code: "V", name: "Valencia" },
    { code: "VA", name: "Valladolid" },
    { code: "VI", name: "Álava" },
    { code: "Z", name: "Zamora" },
    { code: "ZA", name: "Zaragoza" }
];

export default PROVINCES;